spring.application.name: sia-task-config

server.port: 10615

spring.application.cnname: 任务编排中心
management.security.enabled: false
endpoints.health.sensitive: false

eureka.client.serviceUrl.defaultZone: http://your-eureka-host:eureka-port/eureka/
# 注册时使用ip而不是主机名
eureka.instance.preferIpAddress: true
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#authenticate-center
gantryUrl: http://127.0.0.1:9000/

#zooKeeperHosts: 生产建议集群
zooKeeperHosts: 127.0.0.1:2181

spring:
    datasource:
        name: test
        url: jdbc:mysql://your-mysql-address:3306/skyworld_task?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#############################################################
############## mybatis config ###############################
#############################################################
# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: top.dataworks.core.entity
  configuration.default-statement-timeout: 60
#
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql



#############################################################
############## log config ###################################
#############################################################
logging.file: ./logs/${spring.application.name}.


# task根路径
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK根路径，否则默认为SkyWorldOnlineTask
# ZK_ONLINE_ROOT_PATH: SkyWorldOnlineTask
